on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - main

name: Build main branch, upload to "latest" 

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project 
        run: |
          zip example.zip *
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: example.zip
          asset_name: example.zip
          tag: latest
          overwrite: true
